version: "3.7"
services:
    gateway:
        build:
            context: gateway/docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "8070:8080"
            - "8071:8081"

    frontend:
        build:
            context: frontend/docker/development/nginx
        volumes:
            - ./frontend:/app

    frontend-node-cli:
        build:
            context: frontend/docker/development/node
        volumes:
            - ./frontend:/app

    api:
        build:
            context: api/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./api:/app

    api-php-fpm:
        build:
            context: api/docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
        volumes:
            - ./api:/app

    api-php-cli:
        build:
            context: api/docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
        volumes:
            - ./api:/app

    api-postgres:
        image: postgres:13.1-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        volumes:
            - ./api/var/docker/postgres:/var/lib/postgresql/data
        ports:
            - "54371:5432"
